### ISSUE TITLE
Client can't handle bot.Disconnect

### ISSUE THREAD

**Issue by aleksandrzhiliaev** [yasuoza/switchbot#20]
Hey and thanks for your library!

Just found one issue if you are running several apps with switchbot client. So once one of the apps starts connection with the bot:
```golang
bot, err := switchbot.Connect(ctx, addr, timeout)
if err != nil {
  log.Print(err)
  return
 }
defer bot.Disconnect() 
```
it basically occupes `hci` and never releases it until you stop your app.

So from second app I am getting:
```
021/01/13 00:02:42 Cound not initialize a device: can't init hci: no devices available: (hci0: can't down device: device or resource busy)
```

Probably related to the issues in https://github.com/currantlabs/ble/issues/17 didn't check which ble lib you are using.

**Comment by yasuoza** [comment]
BLE library used in this package is based on  currantlabs/ble and currantlabs/ble#17 is already patched.
I've already faced the issue, you can use `-max-retry` option for the situation.

```
switchbot press -max-retry=10 MAC_ADDR
```

**Comment by yasuoza** [comment]
This issue is fixed by v2 release.
